name: tia_nano_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  uuid: ^4.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  connectivity: ^3.0.6
  flutter_svg: ^2.0.9
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.12
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.18.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  auto_route: ^5.0.4
  dio: ^5.3.4
  dio_cookie_manager: ^3.1.0
  pretty_dio_logger: ^1.3.1
  permission_handler: ^10.2.0
  flutter_screenutil: ^5.8.2
  cached_network_image: ^3.3.1
  shimmer: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.2.0 # Build runner for genate code
  injectable_generator: ^1.5.4 # generate injectable depedency injection
  auto_route_generator: ^5.0.0 # for generate router
  # analyzer: ^4.0.0
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
